### ISSUE TITLE
Unable to pod install 

### ISSUE THREAD

**Issue by SandeepAggarwal** [EmergeTools/ETTrace#23]
### Error

RuntimeError - Expected target or target_proxy, from which to fetch a uuid for target ''.Find and clear the PBXTargetDependency entry with uuid 'F4BDB20729B693CA00996FDB' in your .xcodeproj.

### Command

```
/Users/Sandeep/.gem/ruby/3.1.2/bin/pod install
```

### Report

* What did you do?
`pod install`

* What did you expect to happen?
pod install to be successful

* What happened instead?
Failed with the following error
```
RuntimeError - Expected target or target_proxy, from which to fetch a uuid for target ''.Find and clear the PBXTargetDependency entry with uuid 'F4BDB20729B693CA00996FDB' in your .xcodeproj.
/Users/Sandeep/.gem/ruby/3.1.2/gems/xcodeproj-1.21.0/lib/xcodeproj/project/object/target_dependency.rb:62:in `native_target_uuid'
/Users/Sandeep/.gem/ruby/3.1.2/gems/xcodeproj-1.21.0/lib/xcodeproj/project.rb:610:in `map'
/Users/Sandeep/.gem/ruby/3.1.2/gems/xcodeproj-1.21.0/lib/xcodeproj/project.rb:610:in `block in host_targets_for_embedded_target'
/Users/Sandeep/.gem/ruby/3.1.2/gems/xcodeproj-1.21.0/lib/xcodeproj/project.rb:608:in `select'
/Users/Sandeep/.gem/ruby/3.1.2/gems/xcodeproj-1.21.0/lib/xcodeproj/project.rb:608:in `host_targets_for_embedded_target'
/Users/Sandeep/.gem/ruby/3.1.2/gems/cocoapods-1.11.3/lib/cocoapods/installer/analyzer.rb:356:in `block (2 levels) in analyze_host_targets_in_podfile'
/Users/Sandeep/.gem/ruby/3.1.2/gems/cocoapods-1.11.3/lib/cocoapods/installer/analyzer.rb:355:in `each'
/Users/Sandeep/.gem/ruby/3.1.2/gems/cocoapods-1.11.3/lib/cocoapods/installer/analyzer.rb:355:in `flat_map'
/Users/Sandeep/.gem/ruby/3.1.2/gems/cocoapods-1.11.3/lib/cocoapods/installer/analyzer.rb:355:in `block in analyze_host_targets_in_podfile'
/Users/Sandeep/.gem/ruby/3.1.2/gems/cocoapods-1.11.3/lib/cocoapods/installer/analyzer.rb:354:in `each'
/Users/Sandeep/.gem/ruby/3.1.2/gems/cocoapods-1.11.3/lib/cocoapods/installer/analyzer.rb:354:in `analyze_host_targets_in_podfile'
/Users/Sandeep/.gem/ruby/3.1.2/gems/cocoapods-1.11.3/lib/cocoapods/installer/analyzer.rb:467:in `generate_targets'
/Users/Sandeep/.gem/ruby/3.1.2/gems/cocoapods-1.11.3/lib/cocoapods/installer/analyzer.rb:127:in `analyze'
/Users/Sandeep/.gem/ruby/3.1.2/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:416:in `analyze'
/Users/Sandeep/.gem/ruby/3.1.2/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:241:in `block in resolve_dependencies'
/Users/Sandeep/.gem/ruby/3.1.2/gems/cocoapods-1.11.3/lib/cocoapods/user_interface.rb:64:in `section'
/Users/Sandeep/.gem/ruby/3.1.2/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:240:in `resolve_dependencies'
/Users/Sandeep/.gem/ruby/3.1.2/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:161:in `install!'
/Users/Sandeep/.gem/ruby/3.1.2/gems/cocoapods-1.11.3/lib/cocoapods/command/install.rb:52:in `run'
/Users/Sandeep/.gem/ruby/3.1.2/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
/Users/Sandeep/.gem/ruby/3.1.2/gems/cocoapods-1.11.3/lib/cocoapods/command.rb:52:in `run'
/Users/Sandeep/.gem/ruby/3.1.2/gems/cocoapods-1.11.3/bin/pod:55:in `<top (required)>'
/Users/Sandeep/.gem/ruby/3.1.2/bin/pod:25:in `load'
/Users/Sandeep/.gem/ruby/3.1.2/bin/pod:25:in `<main>'
```

### Stack

```
   CocoaPods : 1.11.3
        Ruby : ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [arm64-darwin21]
    RubyGems : 3.3.7
        Host : macOS 13.1 (22C65)
       Xcode : 14.3 (14E222b)
         Git : git version 2.39.2 (Apple Git-143)
Ruby lib dir : /Users/Sandeep/.rubies/ruby-3.1.2/lib
Repositories : cocoapods - git - https://github.com/CocoaPods/Specs.git @ e2a7a88e0839c19fdaf525b5c67a47eb291f34b8
               trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-deintegrate : 1.0.5
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.1
cocoapods-trunk       : 1.6.0
cocoapods-try         : 1.2.0
```

**Comment by noahsmartin** [comment]
Thanks for reporting! We looked into this but haven't been able to reproduce yet on a new clone of the repo.

**Comment by denghuihua** [comment]
Is your problem resolved? I have the same problem and have not resolved yet

**Comment by noahsmartin** [comment]
We just switched to building entirely with SPM so there aren't any project files and no need to pod install, so if you pull the latest main the step that caused this issue is no longer relevant
